name: Automatizar mi APK
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Correr Emulador y Ejecutar APK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29       # Bajamos a API 29 que es más estable y ligera
          target: default     # Usamos la versión estándar (sin Google Play) para que sea más rápido
          arch: x86_64
          profile: Nexus 6    # Un perfil más clásico que consume menos recursos
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
          script: |
            echo "Esperando que el sistema responda..."
            adb wait-for-device
            adb install "Entel Venta Terreno.apk"
            sleep 20
            echo "Tomando captura de pantalla..."
            adb exec-out screencap -p > pantalla.png

      - name: Guardar captura
        uses: actions/upload-artifact@v4
        with:
          name: resultado
          path: ./*.png
